<?php

/**
 * @file
 * Contains steve.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function steve_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the steve module.
    case 'help.page.steve':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Steves awesome module!') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function steve_theme() {
  $theme = [];

  return $theme;
}
